CREATE SCHEMA FCL2;

GO

CREATE TABLE FCL2.VEHICLE_MAKE(
VMAKE_CODE VARCHAR PRIMARY KEY,
VMAKE_NAME VARCHAR(MAX))

CREATE TABLE FCL2.CUSTOMER(
CUST_ID UNIQUEIDENTIFIER PRIMARY KEY,
CUST_FNAME NVARCHAR(MAX),
CUST_LNAME NVARCHAR(MAX),
CUST_PHONE CHAR(12)
)

CREATE TABLE FCL2.VEHICLE_TYPE(
VTYPE_ID UNIQUEIDENTIFIER PRIMARY KEY,
VMAKE_CODE VARCHAR REFERENCES FCL2.VEHICLE_MAKE(VMAKE_CODE),
VMODEL_CODE VARCHAR(MAX),
VTRIM_CODE VARCHAR,
VTYPE_YEAR INT,
VTYPE_DESC VARCHAR(MAX)

)

CREATE TABLE FCL2.VEHICLE(
V_VIN VARCHAR PRIMARY KEY,
CUST_ID UNIQUEIDENTIFIER REFERENCES FCL2.CUSTOMER(CUST_ID),
VTYPE_ID UNIQUEIDENTIFIER REFERENCES FCL2.VEHICLE_TYPE(VTYPE_ID)
)

CREATE TABLE FCL2.INVOICE(
INV_NUM INT PRIMARY KEY,
V_VIN VARCHAR REFERENCES FCL2.VEHICLE(V_VIN),
INV_DATE DATE,
INV_LBR_RATE DECIMAL,
INV_LBR_AMT DECIMAL,
INV_TOTAL_AMT DECIMAL,
INV_PAID_AMT DECIMAL
)

CREATE TABLE FCL2.PAYMENT(
PAY_NUM INT PRIMARY KEY,
CUST_ID UNIQUEIDENTIFIER REFERENCES FCL2.CUSTOMER(CUST_ID),
INV_NUM INT REFERENCES FCL2.INVOICE(INV_NUM),
PAY_AMT DECIMAL
)

CREATE TABLE FCL2.RATE(
RT_CODE VARCHAR PRIMARY KEY,
RT_NAME VARCHAR(MAX),
RT_AMT DECIMAL
)

CREATE TABLE FCL2.VEHICLE_MODEL(
VMAKE_CODE VARCHAR NOT NULL,
VMODEL_CODE VARCHAR NOT NULL,
VMODEL_NAME VARCHAR(MAX),
CONSTRAINT PK_VEHICLE_MODEL PRIMARY KEY(VMAKE_CODE, VMODEL_CODE)
)

CREATE TABLE FCL2.SERVICE(
SVC_ID UNIQUEIDENTIFIER PRIMARY KEY,
SVC_DESC VARCHAR(MAX),
SVC_EST_HRS DECIMAL 
)


CREATE TABLE FCL2.INVOICE_LINE(
INV_NUM INT NOT NULL REFERENCES FCL2.INVOICE(INV_NUM),
LINE_NUM INT NOT NULL,
PART_CODE VARCHAR(MAX),
LINE_QTY INT,
LINE_PRICE DECIMAL,
CONSTRAINT PK_MECHANIC PRIMARY KEY(INV_NUM, LINE_NUM)
)

CREATE TABLE FCL2.MECHANIC(
MECH_ID UNIQUEIDENTIFIER PRIMARY KEY,
MECH_FNAME VARCHAR(MAX) ,
MECH_LANE VARCHAR(MAX) 
)

CREATE TABLE FCL2.JOB(
JOB_NUM INT PRIMARY KEY,
MECH_ID UNIQUEIDENTIFIER REFERENCES FCL2.MECHANIC(MECH_ID),
SVC_ID UNIQUEIDENTIFIER REFERENCES FCL2.SERVICE(SVC_ID),
VTYPE_ID UNIQUEIDENTIFIER,
INV_NUM INT REFERENCES FCL2.INVOICE(INV_NUM),
JOB_EST_HRS DECIMAL,
JOB_ACT_HRS DECIMAL,
JOB_DATE DATE
)

CREATE TABLE FCL2.VEHICLE_TRIM(
VMAKE_CODE VARCHAR NOT NULL,
VMODEL_CODE VARCHAR NOT NULL,
VTRIM_CODE VARCHAR NOT NULL,
VTRIM_NAME VARCHAR(MAX),
CONSTRAINT PK_VEHICLE_TRIM PRIMARY KEY(VMAKE_CODE, VMODEL_CODE, VTRIM_CODE)
)

CREATE TABLE FCL2.PART(
PART_CODE VARCHAR PRIMARY KEY,
PART_MIN_QOH INT,
PART_QOH INT,
PART_DESC VARCHAR(MAX),
PART_PRICE DECIMAL
)

CREATE TABLE FCL2.REQUIRED_PART(
SVC_ID UNIQUEIDENTIFIER NOT NULL REFERENCES FCL2.SERVICE(SVC_ID),
VTYPE_ID UNIQUEIDENTIFIER NOT NULL REFERENCES FCL2.VEHICLE_TYPE(VTYPE_ID),
PART_CODE VARCHAR NOT NULL REFERENCES FCL2.PART(PART_CODE),
REQ_QTY INT,
CONSTRAINT PK_REQUIRED_PART PRIMARY KEY(SVC_ID, VTYPE_ID, PART_CODE)
 
)
CREATE TABLE FCL2.VENDOR(
VEND_ID UNIQUEIDENTIFIER PRIMARY KEY,
VEND_NAME VARCHAR(MAX),
VEND_PHONE CHAR(12),
VEND_CONTACT VARCHAR(MAX)
)

CREATE TABLE FCL2.AVAILABLE_PART(
VEND_ID UNIQUEIDENTIFIER REFERENCES FCL2.VENDOR(VEND_ID),
PART_CODE VARCHAR REFERENCES FCL2.PART(PART_CODE),
CONSTRAINT PK_AVAILABLE_PART PRIMARY KEY(VEND_ID, PART_CODE)
)

CREATE TABLE FCL2.VEHICLE_TYPE_SERVICE(
SVC_ID UNIQUEIDENTIFIER REFERENCES FCL2.SERVICE(SVC_ID),
VTYPE_ID UNIQUEIDENTIFIER REFERENCES FCL2.VEHICLE_TYPE(VTYPE_ID),
CONSTRAINT PK_VEHICLE_TYPE_SERVICE PRIMARY KEY(SVC_ID,VTYPE_ID)
)

create view	MECHANIC_EFFICIENCY(MECH_ID, JOB_ACT_HRS, JOB_EST_HRS, MECH_EFFICIENCY)
AS SELECT  MECH_ID, JOB_ACT_HRS, JOB_EST_HRS, AVG(FCL2.JOB.JOB_ACT_HRS - FCL2.JOB.JOB_EST_HRS) 
FROM FCL2.JOB  
GROUP BY MECH_ID, JOB_ACT_HRS, JOB_EST_HRS;

create view CUSTOMER_EXPENSE(CUST_ID, CUST_FNAME, CUST_LNAME, CUST_PHONE, AGGREGATE)
AS select FCL2.CUSTOMER.CUST_ID, CUST_FNAME,CUST_LNAME,CUST_PHONE, SUM(PAY_AMT)  
from FCL2.CUSTOMER 
INNER JOIN FCL2.PAYMENT ON FCL2.PAYMENT.CUST_ID=FCL2.CUSTOMER.CUST_ID
GROUP BY FCL2.CUSTOMER.CUST_ID, CUST_FNAME, CUST_LNAME, CUST_PHONE